options:
    clustering:
        type: boolean
        description: |
          Enable clustering.

          This feature requires a Mattermost Enterprise Edition licence.
        default: false
    debug:
        type: boolean
        description: Set the Mattermost log level to DEBUG, otherwise INFO.
        default: false
    extra_env:
        type: string
        description: |
          Additional environment values for the Mattermost instance.
          Those will override any previous configuration from this file.
          They should be supplied as a valid JSON string.

          Should be used for tests and debugging purposes.
        default: '{}'
    image_proxy_enabled:
        type: boolean
        description: |
          The image proxy is used by the Mattermost apps to prevent them from connecting directly to remote servers.

          This anonymizes their connections and prevents them from accessing insecure content.

          Currently only the "local" image proxy type is supported.
        default: false
    ingress_whitelist_source_range:
        type: string
        description: |
          A comma-separated list of CIDRs to store in the ingress.kubernetes.io/whitelist-source-range annotation.

          This can be used to lock down access to Mattermost based on source IP address.
        default: ''
    licence:
        type: string
        description: |
          The contents of the licence file as supplied by Mattermost.

          Some features are not available without a licence.  For more
          information, consult the Mattermost documentation.
        default: ''
    mattermost_image_path:
        type: string
        description: |
          The location of the image to use, e.g. "registry.example.com/mattermost:v1".

          Switching to a newer image version will initiate an upgrade of Mattermost.

          This setting is required.
        default: mattermostcharmers/mattermost:v7.1.4-20.04_edge
    mattermost_image_username:
        type: string
        description: |
          The username for accessing the registry specified in mattermost_image_path.
        default: ''
    mattermost_image_password:
        type: string
        description: |
          The password associated with mattermost_image_username for accessing the registry specified in mattermost_image_path.
        default: ''
    max_channels_per_team:
      type: int
      description: |
        Maximum number of channels per team, including both active and deleted channels.
      default: 3000
    max_users_per_team:
      type: int
      description: |
        Maximum number of users per team, including active and inactive users.
      default: 1000
    outbound_proxy:
        type: string
        description: The proxy to use for outbound requests.
        default: ''
    outbound_proxy_exceptions:
        type: string
        description: |
          A list of destinations for which the outbound proxy will not
          be used.

          This can be configured as a set of comma-separated IP
          addresses (e.g. "1.2.3.4"), IP address ranges specified in
          CIDR notation (e.g. "1.2.3.4/8"), or domain names.  An IP
          address or domain name can also include a port number.

          When a domain name is specified, the domain and all of its
          subdomains are matched.  However, a domain name with a
          leading "." only matches the subdomains.  For example,
          "example.com" matches both "example.com" and "sub.example.com"
          while ".example.com" only matches the latter.
        default: ''
    performance_monitoring_enabled:
        type: boolean
        description: |
          When set, Prometheus metrics are exposed via HTTP on port 8067 at the path "/metrics".

          For more information, see https://docs.mattermost.com/deployment/metrics.html

          This feature requires a Mattermost Enterprise Edition licence.
        default: false
    primary_team:
        type: string
        description: |
          The primary team of which users on the server are members.

          When a primary team is set, the options to join other teams or leave the primary team are disabled.

          If the team URL of the primary team is "https://example.mattermost.com/myteam/", then set the value to "myteam".
        default: ''
    push_notification_server:
      type: string
      description: |
        The push notification server to use.
      default: ''
    push_notifications_include_message_snippet:
      type: boolean
      description: |
        If enabled, push notification payloads include the sender, the
        channel, and a snippet of the message itself, which may
        include confidential information.

        If disabled, push notification payloads include the sender,
        the channel, and an ID to let the client retrieve the message
        directly from Mattermost.
      default: false
    site_url:
        type: string
        description: |
          The URL by which the site is reached, including the scheme, e.g. 'http://mysite.example.com'.

          This must be set for all of Mattermost's features to work correctly, and will default to the name of the deployed application.

          For more information, see https://docs.mattermost.com/administration/config-settings.html#site-url
        default: ''
    tls_secret_name:
        type: string
        description: |
          The name of the Kubernetes secret to be associated with the ingress resource.

          This setting is ignored unless site_url begins with "https".
        default: ''
    max_file_size:
        type: int
        description: |
          The maximum file size, in megabytes.

          If there is a reverse proxy in front of Mattermost, it may
          need to be configured to handle the requested size.

          For more information, see the Mattermost documentation.
        default: 5
    s3_enabled:
        type: boolean
        description: |
          Store files and attachments in an S3-compatible object storage service instead of a local directory.
        default: false
    s3_endpoint:
        type: string
        description: |
          The S3 endpoint to use.  This may be a non-Amazon S3-compatible endpoint.

          For more information, see the Mattermost documentation.
        default: 's3.amazonaws.com'
    s3_bucket:
        type: string
        description: |
          The S3 bucket to use.
        default: ''
    s3_region:
        type: string
        description: |
          The S3 region to use.
        default: ''
    s3_access_key_id:
        type: string
        description: |
          The S3 access key ID to use.
        default: ''
    s3_secret_access_key:
        type: string
        description: |
          The S3 secret key to use.
        default: ''
    s3_server_side_encryption:
        type: boolean
        description: |
          Whether to use S3 Server-Side Encryption.

          This requires configuration on the S3 side, as well as a suitable Mattermost licence.
        default: false
    smtp_connection_security:
        type: string
        description: |
          The connection security to use for the outgoing SMTP relay host.
        default: 'STARTTLS'
    smtp_from_address:
        type: string
        description: |
          The notification from address for outgoing mail.
        default: 'noreply+chat@mydomain.local'
    smtp_host:
        type: string
        description: |
          The hostname or IP address of the outgoing SMTP relay host.
        default: ''
    smtp_password:
        type: string
        description: |
          The SMTP AUTH password to use for the outgoing SMTP relay host.
        default: ''
    smtp_port:
        type: int
        description: |
          The port of the outgoing SMTP relay host.
        default: 25
    smtp_reply_to_address:
        type: string
        description: |
          The Reply-To address.
        default: ''
    smtp_user:
        type: string
        description: |
          The SMTP AUTH user to use for the outgoing SMTP relay host.
        default: ''
    sso:
        type: boolean
        description: |
          Whether to use Ubuntu SSO to log in.

          This will not work unless the administrators of login.ubuntu.com have created a suitable SAML config first.

          This feature requires a Mattermost Enterprise Edition licence.
        default: false
    use_canonical_defaults:
        type: boolean
        description: |
          If set, apply miscellaneous Mattermost settings as used by Canonical.
        default: false
    use_experimental_saml_library:
        type: boolean
        description: |
          If set, use the built-in Mattermost SAML library. Otherwise, use xmlsec1 to verify logins.
        default: true
