options:
    mattermost_port:
        type: int
        description: The port number for Mattermost to listen to.
        default: 8000
    open_server:
        type: boolean
        description: Allows users to sign up from the root page without an invite
        default: false
