options:
    debug:
        type: boolean
        description: Set the Mattermost log level to DEBUG, otherwise INFO.
        default: false
    ingress_whitelist_source_range:
        type: string
        description: |
          A comma-separated list of CIDRs to storein the ingress.kubernetes.io/whitelist-source-range annotation.

          This can be used to lock down access to Mattermost based on source IP address.
        default: ''
    open_server:
        type: boolean
        description: Allows users to sign up from the root page without an invite
        default: false
    outbound_proxy:
        type: string
        description: The proxy to use for outbound requests.
        default: ''
    outbound_proxy_exceptions:
        type: string
        description: |
          A list of destinations for which the outbound proxy will not
          be used.

          This can be configured as a set of comma-separated IP
          addresses (e.g. "1.2.3.4"), IP address ranges specified in
          CIDR notation (e.g. "1.2.3.4/8"), or domain names.  An IP
          address or domain name can also include a port number.

          When a domain name is specified, the domain and all of its
          subdomains are matched.  However, a domain name with a
          leading "." only matches the subdomains.  For example,
          "example.com" matches both "example.com" and "sub.example.com"
          while ".example.com" only matches the latter.
        default: ''
    site_url:
        type: string
        description: |
          The URL by which the site is reached.  This must be set for all of Mattermost's features to work correctly.

          For more information, see https://docs.mattermost.com/administration/config-settings.html#site-url
        default: ''
    tls_secret_name:
        type: string
        description: |
          The name of the Kubernetes secret to be associated with the ingress resource.

          This setting is ignored unless site_url begins with "https".
        default: ''
    max_file_size:
        type: int
        description: |
          The maximum file size, in megabytes.

          If there is a reverse proxy in front of Mattermost, it may
          need to be configured to handle the requested size.

          For more information, see the Mattermost documentation.
        default: 5
    s3_enabled:
        type: boolean
        description: |
          Store files and attachments in an S3-compatible object storage service instead of a local directory.
        default: false
    s3_endpoint:
        type: string
        description: |
          The S3 endpoint to use.  This may be a non-Amazon S3-compatible endpoint.

          For more information, see the Mattermost documentation.
        default: 's3.amazonaws.com'
    s3_bucket:
        type: string
        description: |
          The S3 bucket to use.
        default: ''
    s3_region:
        type: string
        description: |
          The S3 region to use.
        default: ''
    s3_access_key_id:
        type: string
        description: |
          The S3 access key ID to use.
        default: ''
    s3_secret_access_key:
        type: string
        description: |
          The S3 secret key to use.
        default: ''
    s3_server_side_encryption:
        type: boolean
        description: |
          Whether to use S3 Server-Side Encryption.

          This requires configuration on the S3 side, as well as a suitable Mattermost licence.
        default: false
