{
 "title": "Mattermost Performance Monitoring v2",
 "description": "A dashboard to monitor complete Mattermost application performance",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheusds", "label": "Prometheus datasource", "query": "prometheus" },
   { "name": "juju_model", "label": "Juju model", "query": { "query": "label_values(up,juju_model)" } },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\"},juju_model_uuid)"
    }
   },
   {
    "name": "juju_application",
    "label": "Juju application",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "juju_unit",
    "label": "Juju unit",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_application=~\"$juju_application\"},juju_unit)"
    }
   },
   {
    "name": "top_db_count",
    "label": "Top DB Count Filter",
    "query": {
     "query": "label_values(mattermost_db_store_time_count{juju_model=~\"$juju_model\",juju_application=~\"$juju_application\"}, method)"
    }
   },
   {
    "name": "top_db_latency",
    "label": "Top DB Latency Filter",
    "query": {
     "query": "label_values(mattermost_db_store_time_sum{juju_model=~\"$juju_model\",juju_application=~\"$juju_application\"}, method)"
    }
   },
   {
    "name": "top_api_count",
    "label": "Top API Count Filter",
    "query": {
     "query": "label_values(mattermost_api_time_count{juju_model=~\"$juju_model\",juju_application=~\"$juju_application\"}, handler)"
    }
   },
   {
    "name": "top_api_latency",
    "label": "Top API Latency Filter",
    "query": {
     "query": "label_values(mattermost_api_time_sum{juju_model=~\"$juju_model\",juju_application=~\"$juju_application\"}, handler)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Websockets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Websocket Buffer Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mattermost_websocket_broadcast_buffer_size{juju_model=~\"$juju_model\", juju_application=~\"$juju_application\", juju_unit=~\"$juju_unit\"})",
     "legendFormat": "Buffer size"
    }
   ]
  },
  {
   "title": "Websocket Broadcasts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mattermost_websocket_broadcasts_total{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\", juju_unit=~\"$juju_unit\"}[5m])) by (juju_model, juju_application, juju_unit, name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Websocket Reconnects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(mattermost_websocket_reconnects_total{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\", juju_unit=~\"$juju_unit\"}[10m])) by (juju_model, juju_application, juju_unit)",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Websocket Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mattermost_websocket_event_total{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\", juju_unit=~\"$juju_unit\"}[5m])) by (juju_model, juju_application, juju_unit, type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Application Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mattermost_http_requests_total{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[1m])",
     "legendFormat": "{{juju_unit}}"
    },
    {
     "expr": "sum(rate(mattermost_http_requests_total{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DB Calls per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mattermost_db_store_time_count{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[5m])) by (juju_model, juju_application, juju_unit)",
     "legendFormat": "{{juju_unit}}"
    },
    {
     "expr": "sum(rate(mattermost_db_store_time_count{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "API Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(mattermost_api_time_bucket{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[1m])) by (juju_model, juju_application, juju_unit, le))",
     "legendFormat": "p99-{{juju_unit}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(mattermost_api_time_bucket{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[1m])) by (juju_model, juju_application, juju_unit, le))",
     "legendFormat": "p50-{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Store latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(mattermost_db_store_time_bucket{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[1m])) by (juju_model, juju_application, juju_unit, le))",
     "legendFormat": "p99-{{juju_unit}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(mattermost_db_store_time_bucket{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[1m])) by (juju_model, juju_application, juju_unit, le))",
     "legendFormat": "p50-{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Top 10 DB Calls by Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(mattermost_db_store_time_count{method=~\"$top_db_count\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[5m])) by (juju_model, juju_application, juju_unit, method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Top 10 API Requests by Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(mattermost_api_time_count{handler=~\"$top_api_count\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[5m])) by (juju_model, juju_application, juju_unit, handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Top 10 DB calls by duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(mattermost_db_store_time_sum{method=~\"$top_db_latency\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[5m])) by (juju_model, juju_application, juju_unit, method) / sum(increase(mattermost_db_store_time_count{method=~\"$top_db_latency\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[5m])) by (juju_model, juju_application, juju_unit, method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Top 10 API requests by duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(mattermost_api_time_sum{handler=~\"$top_api_latency\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[5m])) by (juju_model, juju_application, juju_unit, handler) / sum(increase(mattermost_api_time_count{handler=~\"$top_api_latency\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[5m])) by (juju_model, juju_application, juju_unit, handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Channel Load Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.99,\n  sum by (le, juju_model, juju_application, juju_unit)(\n    rate(mattermost_api_time_bucket{handler=\"getPostsForChannelAroundLastUnread\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[5m])\n  )\n)",
     "legendFormat": "p99-{{juju_unit}}"
    },
    {
     "expr": "histogram_quantile (\n  0.50,\n  sum by (le, juju_model, juju_application, juju_unit)(\n    rate(mattermost_api_time_bucket{handler=\"getPostsForChannelAroundLastUnread\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[5m])\n  )\n)",
     "legendFormat": "p50-{{juju_unit}}"
    }
   ]
  },
  {
   "title": "CreatePost duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile (\n  0.99,\n  sum by (le, juju_model, juju_application, juju_unit)(\n    rate(mattermost_api_time_bucket{handler=\"createPost\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[5m])\n  )\n)",
     "legendFormat": "p99-{{juju_unit}}"
    },
    {
     "expr": "histogram_quantile (\n  0.50,\n  sum by (le, juju_model, juju_application, juju_unit)(\n    rate(mattermost_api_time_bucket{handler=\"createPost\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[5m])\n  )\n)",
     "legendFormat": "p50-{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Number of connected devices (WebSocket Connections)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mattermost_http_websockets_total{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}",
     "legendFormat": "{{juju_unit}} - {{ origin_client}}"
    },
    {
     "expr": "sum(mattermost_http_websockets_total{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(mattermost_http_websockets_total{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}) by (juju_model, juju_application, juju_unit, origin_client)",
     "legendFormat": "Total - {{ origin_client }}"
    }
   ]
  },
  {
   "title": "DB Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mattermost_db_master_connections_total{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"})",
     "legendFormat": "master"
    },
    {
     "expr": "sum(mattermost_db_read_replica_connections_total{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"})",
     "legendFormat": "replica"
    }
   ]
  },
  {
   "title": "Connection Pool (Replica)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(go_sql_open_connections{db_name=~\"replica.*\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"})",
     "legendFormat": "open_conns"
    },
    {
     "expr": "sum(go_sql_in_use_connections{db_name=~\"replica.*\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"})",
     "legendFormat": "in_use_conns"
    },
    {
     "expr": "sum(rate(go_sql_wait_count_total{db_name=~\"replica.*\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[5m]))",
     "legendFormat": "wait_count"
    },
    {
     "expr": "sum(rate(go_sql_max_idle_closed_total{db_name=~\"replica.*\",juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[5m]))",
     "legendFormat": "max_idle_closed"
    },
    {
     "expr": "sum(rate(go_sql_max_idle_time_closed_total{db_name=~\"replica.*\",juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[5m]))",
     "legendFormat": "max_idle_time_closed"
    }
   ]
  },
  {
   "title": "Connection Pool (Master)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(go_sql_open_connections{db_name=\"master\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"})",
     "legendFormat": "open_conns"
    },
    {
     "expr": "sum(go_sql_in_use_connections{db_name=\"master\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"})",
     "legendFormat": "in_use_conns"
    },
    {
     "expr": "sum(rate(go_sql_wait_count_total{db_name=\"master\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[5m]))",
     "legendFormat": "wait_count"
    },
    {
     "expr": "sum(rate(go_sql_max_idle_closed_total{db_name=\"master\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[5m]))",
     "legendFormat": "max_idle_closed"
    },
    {
     "expr": "sum(rate(go_sql_max_idle_time_closed_total{db_name=\"master\",juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[5m]))",
     "legendFormat": "max_idle_time_closed"
    }
   ]
  },
  {
   "title": "Replica Lag",
   "type": "timeseries",
   "description": "This needs to be configured in config.json for it to work",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mattermost_db_replica_lag_time{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Cluster Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Health",
   "type": "timeseries",
   "description": "Lower numbers are better, and zero means \"totally healthy\".",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mattermost_cluster_cluster_health_score{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Cluster Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(mattermost_cluster_cluster_request_duration_seconds_bucket{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[5m])) by (le, juju_model, juju_application, juju_unit))",
     "legendFormat": "p99-{{juju_unit}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(mattermost_cluster_cluster_request_duration_seconds_bucket{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[5m])) by (le, juju_model, juju_application, juju_unit))",
     "legendFormat": "p50-{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Cluster Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mattermost_cluster_cluster_request_duration_seconds_count{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[5m])) by (juju_model, juju_application, juju_unit)",
     "legendFormat": "{{juju_unit}}"
    },
    {
     "expr": "sum(rate(mattermost_cluster_cluster_request_duration_seconds_count{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Job Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mattermost_jobs_active{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}",
     "legendFormat": "{{juju_unit}}"
    },
    {
     "expr": "sum(mattermost_jobs_active{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "System Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilization Percentage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(mattermost_process_cpu_seconds_total{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}[5m])* 100",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Heap Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}",
     "legendFormat": "{{juju_unit}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"}",
     "legendFormat": "{{juju_unit}}"
    },
    {
     "expr": "sum(go_goroutines{juju_application=~\"$juju_application\", juju_model=~\"$juju_model\"})",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}