#!/bin/bash

ADMIN_USER=$(action-get user)

COMMAND=$(/mattermost/bin/mattermost roles system_admin ${ADMIN_USER})
if [ $? != 0 ]; then
    action-fail "Failed to run grant-admin-role. Output was ${COMMAND}"
else
    echo "Ran grant-admin-role on user \"${ADMIN_USER}\". The user will need "
    echo "to log out and log back in to Mattermost to fully receive their "
    echo "permissions upgrade."
fi
