name: Tests

on:
  pull_request:

jobs:
  unit-test:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - run: tox -e unit
